### ISSUE TITLE
I cannot find list of forbidden character for header of fasta

### ISSUE THREAD

**Issue by svicario** [Pbdas/epa-ng#11]
I got with my data set the error
"... fasta_getnext failed: Illegal header line in query fasta file"
my headers look like 
">Read_3_sample=RF-pre-50cells-8h_S30_L001_R_size=121_"
So nothing clearly wrong. 
But maybe with a list of forbidden character I can find a way to squeeze the info ( size=, is needed for post processing)

**Comment by Pbdas** [comment]
Hi svicario,
that error seems to be related the ">" symbol not being located at the beginning of a line. I cannot reproduce the error with just the sample header you posted; the "=" symbol parses correctly for me.

Please ensure that the file is a valid fasta file. If it is and the error persists, please consider sending me a zipped subsample of your file so that I can test for myself.

**Comment by svicario** [comment]
I found out that the problem was in the reference alignment and not in the query. So the bug is the message that ask to check the query fasta file and not the ref. Indeed in the reference header name coming from silvaDB has this kind of structure
>D50541       DE 1	1411	1411bp	rna	Abiotrophia defectiva	Aerococcaceae
generally programs stop to read after the multiple space but I sanitized as such 
>D50541
and now it run.
thanks for your work
