### ISSUE TITLE
Treeparsing error

### ISSUE THREAD

**Issue by gavinmdouglas** [Pbdas/epa-ng#12]
Hi there,

I'm using the latest version of epa-ng and am getting this error when I try to run it:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Treeparsing failed!
```

The input tree **(edit: which is in newick format)** is unrooted and is based on 16,539 sequences. Any idea how I can better troubleshoot what is causing the error?

Thanks,

Gavin

**Comment by lczech** [comment]
Hi @gavinmdouglas,

good that you made the edit, I was just about to ask whether the file is Newick ;-)
Does it have any further annotations in it, like support values and the like?
If yes, try removing them. If not, please can you send us the file?

Lucas

**Comment by Pbdas** [comment]
Hi Gavin,

I just pushed a quick fix to the master branch improving the error message. Please do a pull, recompile and rerun!

Pierre

**Comment by lczech** [comment]
That was quickly solved. By the way, for the future: We prefer discussing problems with input files on our [Google Group](https://groups.google.com/forum/#!forum/raxml). But as this started as an issue with the program itself, let's continue here ;-) (I hope @Pbdas agrees)

What program did you use to infer your tree? Usually, I'd expect that do produce bifurcating files, otherwise it does not make much sense to conduct phylogenetic placement. Also, for best results, it should be a maximum likelihood tree, because `epa-ng` is also likelihood-based.

As for aligning query sequences, we use [PaPaRa](https://sco.h-its.org/exelixis/web/software/papara/index.html). It uses the tree and the reference alignment to get a phylogenetically informed alignment for each query sequence. There is also a tool called `hmmalign`, which is part of the `HMMER` suite, I think. Never have used that however.

**Comment by gavinmdouglas** [comment]
Ok good to know about the google group. I used FastTree to generate the tree: I have been testing RAxML as well, but so far the phylogenies haven't been very different. I haven't heard of PaPaRa, it sounds useful. Thanks for your thoughts!
