### ISSUE TITLE
A bit unclear model notation

### ISSUE THREAD

**Issue by novigit** [Pbdas/epa-ng#23]
Hi!
I would like to pass on the model to EPA-ng manually for the command line, for example

--model GTR{0.7/1.8/1.2/0.6/3.0/1.0}+F+R9{r1/r2/.../r9}{w1/w2/.../w9}

The order of relative rates in the GTR{} is A-C, A-G, A-T, C-G, C-T, G-T ?

I'm just double checking this, since it is not explicitly stated in the readme. 

Could you also update the README for this?

Cheers,

Joran

**Comment by Pbdas** [comment]
Hi Joran,

yes, that is in fact the order, due to the compatibility with IQTree :)

I've been meaning to add a much more extensive wiki, similar to the on in raxml-ng; its on my list. I will also forward the request to the developer of raxml-ng, who maintains the doumentation entry I link to in the wiki.

Happy Placement,
Pierre

**Comment by novigit** [comment]
Ok! Thanks for confirming so quickly!
