### ISSUE TITLE
Setting random seed

### ISSUE THREAD

**Issue by gavinmdouglas** [Pbdas/epa-ng#25]
Hi @Pbdas,

Is there any plan to allow users to set a random seed at some point to ensure reproducible results? I believe that at the heuristic pre-placement stage there is randomness that can cause slightly differing results. I'm not sure how feasible setting the random seed at the start of this process would be.

Thanks for your thoughts!

**Comment by Pbdas** [comment]
Hi @gavinmdouglas,

there isn't any built in randomness that I am aware of... do you have any concrete examples?

Theoretically under multiple threads there could be some variation, since this will vary the ordering of the pre-placement results. However before "candidate selection", where for each query a set of branches to do placement properly is identified, that list is always sorted. So the only variation could come from entries in this list having the "same" likelihood weight ratio.

**Comment by gavinmdouglas** [comment]
@Pbdas - sure I've created a simple example that I will email to you.
