### ISSUE TITLE
Hello,I find issue running this program 

### ISSUE THREAD

**Issue by Kangjinkyeong** [Pbdas/epa-ng#39]
Hello Pierre Barbera,
First, thank you for making this program :) sadly even though you made a very kind protocol for beginners to follow like me 
my script seems to keep on stopped while running.

INFO Selected: Output dir: ./
INFO Selected: Query file: Onlyotualigned.fasta
INFO Selected: Tree file: RAxML_fastTree.reference_aligned.tree
INFO Selected: Reference MSA: reference_aligned.fasta
INFO Selected: Automatic switching of use of per rate scalers
INFO Selected: Preserving the root of the input tree
INFO Selected: Specified model: GTR+G+F
INFO     ______ ____   ___           _   __ ______
        / ____// __ \ /   |         / | / // ____/
       / __/  / /_/ // /| | ______ /  |/ // / __  
      / /___ / ____// ___ |/_____// /|  // /_/ /  
     /_____//_/    /_/  |_|      /_/ |_/ \____/ (v0.3.8)
ERR  Setting tip states failed for sequence: YP_004324525.1
ERR  message: Illegal state code in tip "E"

This is the issue
My data contains Amino Acids
and aligned by MUSCLE and made Reference Tree with RAxML 
I think I have a problem with my datasets but, I can't point the exact issue 
could you pls help me with this issue?
Thank you, in advance 
[reference_aligned.txt](https://github.com/Pbdas/epa-ng/files/7278303/reference_aligned.txt)

**Comment by Pbdas** [comment]
Hi @Kangjinkyeong,

please try the following: instead of specifying `GTR+G+F` as model (which takes default model parameters!), please pass the 
RAxML_info file that was created as a result of your tree search, via `--model`. This will have the two effects of: 1) selecting an amino acid model (i.e. `PROTGTR` instead of `GTR`) and 2) supplying the actually correct model parameters that belong with the tree.

If that RAxML_info file somehow doesn't work, please try to re-estimate the model parameters using RAxML-NG (which is the currently supported version). See here for details: https://github.com/Pbdas/epa-ng#basic

Let me know if it works!
Pierre

**Comment by Kangjinkyeong** [comment]
Thank you for the fast response
but I don't understand your guidelines
first. I think you wanted my file so I will give you that.
and from your email, I guess the model I used for making the reference tree
and EPA tree model doesn't match
I got lost in here which model should I use??
I'm very new to this GitHub system so I have a hard time understanding all
those, could you pls explain a little bit further??

Thank you!!!!
Sincerely Jinkyeong.

2021년 10월 4일 (월) 오후 11:12, Pierre Barbera ***@***.***>님이 작성:

**Comment by Pbdas** [comment]
Hi Jinkyeong,

there are two problems:
- you told EPA-ng that your data is DNA (by setting the model as "GTR") when it is actually amino acids
- you passed the model string "GTR+G", which uses default values for the model parameters. This is bad, because it will result in the wrong likelihoods being calculated.

Here is how you solve both issues:

When you built your reference tree, RAxML produced multiple files. One of them should be called something like "RAxML_info.reference_aligned" (I'm guessing). This file has all the model information that EPA-ng needs. EPA-ng can take that information directly from the file, so in your call to EPA-ng, you can simply do "... --model RAxML_info.reference_aligned" (or however the file is called).

If you don't have that file (or if EPA-ng throws an error) I recommend re-creating it using the newer program called raxml-ng, like so:

```
raxml-ng --evaluate --msa reference_aligned.fasta --tree RAxML_fastTree.reference_aligned.tree --prefix info --model PROTGTR+G
```

That should create a file called "info.raxml.bestModel", which you can then pass to EPA-ng via the "--model" parameter.

Let me know if that works for you!
Pierre
